export type Json = | string | number | boolean | null | { [key: string]: Json } | Json[]

export interface Database {
  public: {
    Tables: {
      students: {
        Row: { // the data type of a single row
          id: string
          name: string
          email: string
        }
        Insert: { // the data type to insert a new row
          id?: string // generated by default
          name: string
          email: string
        }
        Update: { // the data type to update a row
          id?: string
          name?: string
          email?: string
        }
      }
    }
  }
}
